// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// box_kernel
double box_kernel(double x);
RcppExport SEXP _nppack_box_kernel(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(box_kernel(x));
    return rcpp_result_gen;
END_RCPP
}
// normal_kernel
double normal_kernel(double x);
RcppExport SEXP _nppack_normal_kernel(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(normal_kernel(x));
    return rcpp_result_gen;
END_RCPP
}
// imput_np
List imput_np(arma::vec& x_vec, arma::vec& y_vec, arma::vec& d_vec, double h, int type);
RcppExport SEXP _nppack_imput_np(SEXP x_vecSEXP, SEXP y_vecSEXP, SEXP d_vecSEXP, SEXP hSEXP, SEXP typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type x_vec(x_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type y_vec(y_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type d_vec(d_vecSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< int >::type type(typeSEXP);
    rcpp_result_gen = Rcpp::wrap(imput_np(x_vec, y_vec, d_vec, h, type));
    return rcpp_result_gen;
END_RCPP
}
// np_cv
arma::vec np_cv(arma::vec& trax_vec, arma::vec& tray_vec, arma::vec& trad_vec, arma::vec& tesx_vec, arma::vec& tesy_vec, arma::vec& tesd_vec, arma::vec& h_vec, int type);
RcppExport SEXP _nppack_np_cv(SEXP trax_vecSEXP, SEXP tray_vecSEXP, SEXP trad_vecSEXP, SEXP tesx_vecSEXP, SEXP tesy_vecSEXP, SEXP tesd_vecSEXP, SEXP h_vecSEXP, SEXP typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type trax_vec(trax_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type tray_vec(tray_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type trad_vec(trad_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type tesx_vec(tesx_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type tesy_vec(tesy_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type tesd_vec(tesd_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type h_vec(h_vecSEXP);
    Rcpp::traits::input_parameter< int >::type type(typeSEXP);
    rcpp_result_gen = Rcpp::wrap(np_cv(trax_vec, tray_vec, trad_vec, tesx_vec, tesy_vec, tesd_vec, h_vec, type));
    return rcpp_result_gen;
END_RCPP
}
// imput_npt
List imput_npt(arma::vec& x_vec, arma::vec& y_vec, arma::vec& d_vec, double h, int type, double c);
RcppExport SEXP _nppack_imput_npt(SEXP x_vecSEXP, SEXP y_vecSEXP, SEXP d_vecSEXP, SEXP hSEXP, SEXP typeSEXP, SEXP cSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type x_vec(x_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type y_vec(y_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type d_vec(d_vecSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< int >::type type(typeSEXP);
    Rcpp::traits::input_parameter< double >::type c(cSEXP);
    rcpp_result_gen = Rcpp::wrap(imput_npt(x_vec, y_vec, d_vec, h, type, c));
    return rcpp_result_gen;
END_RCPP
}
// npt_cv
arma::vec npt_cv(arma::vec& trax_vec, arma::vec& tray_vec, arma::vec& trad_vec, arma::vec& tesx_vec, arma::vec& tesy_vec, arma::vec& tesd_vec, arma::vec& h_vec, int type, double c);
RcppExport SEXP _nppack_npt_cv(SEXP trax_vecSEXP, SEXP tray_vecSEXP, SEXP trad_vecSEXP, SEXP tesx_vecSEXP, SEXP tesy_vecSEXP, SEXP tesd_vecSEXP, SEXP h_vecSEXP, SEXP typeSEXP, SEXP cSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type trax_vec(trax_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type tray_vec(tray_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type trad_vec(trad_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type tesx_vec(tesx_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type tesy_vec(tesy_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type tesd_vec(tesd_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type h_vec(h_vecSEXP);
    Rcpp::traits::input_parameter< int >::type type(typeSEXP);
    Rcpp::traits::input_parameter< double >::type c(cSEXP);
    rcpp_result_gen = Rcpp::wrap(npt_cv(trax_vec, tray_vec, trad_vec, tesx_vec, tesy_vec, tesd_vec, h_vec, type, c));
    return rcpp_result_gen;
END_RCPP
}
// pse_npt
List pse_npt(arma::vec& x_vec, arma::vec& y_vec, arma::vec& d_vec, double h, int type, double c);
RcppExport SEXP _nppack_pse_npt(SEXP x_vecSEXP, SEXP y_vecSEXP, SEXP d_vecSEXP, SEXP hSEXP, SEXP typeSEXP, SEXP cSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type x_vec(x_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type y_vec(y_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type d_vec(d_vecSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< int >::type type(typeSEXP);
    Rcpp::traits::input_parameter< double >::type c(cSEXP);
    rcpp_result_gen = Rcpp::wrap(pse_npt(x_vec, y_vec, d_vec, h, type, c));
    return rcpp_result_gen;
END_RCPP
}
// gpi_fun
List gpi_fun(arma::vec& x_vec, arma::vec& d_vec, arma::vec& x_new, double h, int type);
RcppExport SEXP _nppack_gpi_fun(SEXP x_vecSEXP, SEXP d_vecSEXP, SEXP x_newSEXP, SEXP hSEXP, SEXP typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type x_vec(x_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type d_vec(d_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type x_new(x_newSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< int >::type type(typeSEXP);
    rcpp_result_gen = Rcpp::wrap(gpi_fun(x_vec, d_vec, x_new, h, type));
    return rcpp_result_gen;
END_RCPP
}
// rcpparma_hello_world
arma::mat rcpparma_hello_world();
RcppExport SEXP _nppack_rcpparma_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpparma_hello_world());
    return rcpp_result_gen;
END_RCPP
}
// rcpparma_outerproduct
arma::mat rcpparma_outerproduct(const arma::colvec& x);
RcppExport SEXP _nppack_rcpparma_outerproduct(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpparma_outerproduct(x));
    return rcpp_result_gen;
END_RCPP
}
// rcpparma_innerproduct
double rcpparma_innerproduct(const arma::colvec& x);
RcppExport SEXP _nppack_rcpparma_innerproduct(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpparma_innerproduct(x));
    return rcpp_result_gen;
END_RCPP
}
// rcpparma_bothproducts
Rcpp::List rcpparma_bothproducts(const arma::colvec& x);
RcppExport SEXP _nppack_rcpparma_bothproducts(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpparma_bothproducts(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_nppack_box_kernel", (DL_FUNC) &_nppack_box_kernel, 1},
    {"_nppack_normal_kernel", (DL_FUNC) &_nppack_normal_kernel, 1},
    {"_nppack_imput_np", (DL_FUNC) &_nppack_imput_np, 5},
    {"_nppack_np_cv", (DL_FUNC) &_nppack_np_cv, 8},
    {"_nppack_imput_npt", (DL_FUNC) &_nppack_imput_npt, 6},
    {"_nppack_npt_cv", (DL_FUNC) &_nppack_npt_cv, 9},
    {"_nppack_pse_npt", (DL_FUNC) &_nppack_pse_npt, 6},
    {"_nppack_gpi_fun", (DL_FUNC) &_nppack_gpi_fun, 5},
    {"_nppack_rcpparma_hello_world", (DL_FUNC) &_nppack_rcpparma_hello_world, 0},
    {"_nppack_rcpparma_outerproduct", (DL_FUNC) &_nppack_rcpparma_outerproduct, 1},
    {"_nppack_rcpparma_innerproduct", (DL_FUNC) &_nppack_rcpparma_innerproduct, 1},
    {"_nppack_rcpparma_bothproducts", (DL_FUNC) &_nppack_rcpparma_bothproducts, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_nppack(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
