# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

box_kernel <- function(x) {
    .Call(`_nppack_box_kernel`, x)
}

normal_kernel <- function(x) {
    .Call(`_nppack_normal_kernel`, x)
}

imput_np <- function(x_vec, y_vec, d_vec, h, type) {
    .Call(`_nppack_imput_np`, x_vec, y_vec, d_vec, h, type)
}

np_cv <- function(trax_vec, tray_vec, trad_vec, tesx_vec, tesy_vec, tesd_vec, h_vec, type) {
    .Call(`_nppack_np_cv`, trax_vec, tray_vec, trad_vec, tesx_vec, tesy_vec, tesd_vec, h_vec, type)
}

imput_npt <- function(x_vec, y_vec, d_vec, h, type, c = 0.2) {
    .Call(`_nppack_imput_npt`, x_vec, y_vec, d_vec, h, type, c)
}

npt_cv <- function(trax_vec, tray_vec, trad_vec, tesx_vec, tesy_vec, tesd_vec, h_vec, type, c) {
    .Call(`_nppack_npt_cv`, trax_vec, tray_vec, trad_vec, tesx_vec, tesy_vec, tesd_vec, h_vec, type, c)
}

pse_npt <- function(x_vec, y_vec, d_vec, h, type, c = 0.2) {
    .Call(`_nppack_pse_npt`, x_vec, y_vec, d_vec, h, type, c)
}

gpi_fun <- function(x_vec, d_vec, x_new, h, type) {
    .Call(`_nppack_gpi_fun`, x_vec, d_vec, x_new, h, type)
}

rcpparma_hello_world <- function() {
    .Call(`_nppack_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_nppack_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_nppack_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_nppack_rcpparma_bothproducts`, x)
}

